### PR TITLE
Achievements

### PR DESCRIPTION
**Pull request by graysonlottes**
### Summary
Achievements Page is now available. There are four achievements. One for your first kill, one for 10 kills, one for creating your first world, and one for creating 10 worlds. These achievements will show up on your screen whether you have progress towards them or not. When there is progress towards them it shows in the Achievements tab. Once an achievement is ready to be claimed, a "Claim Reward" button pops up. When you click that button, your shards balance increases by however much the rewards is for that achievement. After claiming, it just puts a "You have already claimed this reward. sentence where the claim reward button used to be.

### Screenshots
Screenshot (48)

### Issue Type
🚀 Feature Request

### Checklist
-  I have checked for similar issues.
- I have attached relevant screenshots.
- I have marked my issue type correctly.

### CODE REVIEW

**Comment by graysonlottes** [comment]
Also wanted to add that I am confused why the checks github workflow action isnt going through. But when running all the tests, I get 100% code coverage, rubocop is fine, and there are cucumber tests.

**Comment by Spencer-Holman** [comment]
Grayson I noticed your rubocop checks failed

**Comment by Spencer-Holman** [comment]
Grayson your rubocop checks failed again

**Review by Spencer-Holman — APPROVED** [review]
Achievements in place work - might be a good idea to add an achievement for first  login later so that we can easily demo the system

**Pull request merged**
