### PR TITLE
shop and inventory system page

### PR DESCRIPTION
**Pull request by nickhansel**
https://github.com/user-attachments/assets/98049b18-be9d-4fca-acdb-bfded6ed2796

### CODE REVIEW

**Comment by graysonlottes** [comment]
I see the shop functionality in the code, but when running the app and clicking the shop tab, I can not see any of the items available for purchase. Spencer and I are looking right now for the issue, please let us know if you have any insight. Otherwise, looks great!

**Comment by Spencer-Holman** [comment]
fix the shop asset issue, but then lgtm

**Comment by nickhansel** [comment]
> e issue, please let us know if you have any insight. Otherwise, looks great!

@graysonlottes run rails db:seed

**Review by graysonlottes — APPROVED** [review]
@nickhansel thanks for the help, works fine now

**Pull request merged**
